; Listing generated by Microsoft (R) Optimizing Compiler Version 19.43.34810.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__990F5430_Math@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?Multiply@@YAHXZ				; Multiply
PUBLIC	__JustMyCode_Default
EXTRN	__CheckForDebuggerJustMyCode:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$?Multiply@@YAHXZ DD imagerel $LN4
	DD	imagerel $LN4+26
	DD	imagerel $unwind$?Multiply@@YAHXZ
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?Multiply@@YAHXZ DD 010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?Multiply@@YAHXZ
_TEXT	SEGMENT
?Multiply@@YAHXZ PROC					; Multiply, COMDAT
; File C:\Vývoj\C++\PrvniC2xPlusProjekt\PrvniC2xPlusProjekt\Math.cpp
; Line 4
$LN4:
	sub	rsp, 40					; 00000028H
	lea	rcx, OFFSET FLAT:__990F5430_Math@cpp
	call	__CheckForDebuggerJustMyCode
	mov	eax, 10
; Line 6
	add	rsp, 40					; 00000028H
	ret	0
?Multiply@@YAHXZ ENDP					; Multiply
_TEXT	ENDS
END
